<?php

$title = 'Mon Stock : ';
$title .= $entrepot->nom;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <a class="btn" href="<?php echo $this->url('stock', array('action'=>'add', 'id' => $entrepot->id));?>">Ajouter un produit</a>
</p>

<?php	if ($stocks) :  ?>

<table class="table">
<tr>
    <th>Produit</th>
	<th>Solde</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($stocks as $stock) : ?>
<tr>
    <td><?php echo $this->escapeHtml($stock->libelle);?></td>
    <td><?php echo $this->escapeHtml($stock->quantite);?></td>
    <td>
		<a class="btn" href="<?php echo $this->url('stock',
            array('action'=>'edit', 'id' => $stock->id));?>">Modifier</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php else : ?>

<p> Aucun produit au stock </p>

<?php endif; ?>