<?php
// module/Album/view/produit/produit/index.phtml:

$title = 'Mon Stock : ';
$title .= $entrepot->nom;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <a href="<?php echo $this->url('stock', array('action'=>'add', 'id' => $entrepot->id));?>">Ajouter un produit</a>
</p>

<?php	if ($stocks) :  ?>

<table class="table">
<tr>
    <th>Produit</th>
	<th>Quantite</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($stocks as $stock) : var_dump($stock);?>
<tr>
    <td><?php echo $this->escapeHtml($stock->libelle);?></td>
    <td><?php echo $this->escapeHtml($stock->quantite);?></td>
    <td>
		<a href="<?php echo $this->url('stock',
            array('action'=>'index', 'id' => $entrepot->id));?>">Voir stock</a>
        <a href="<?php echo $this->url('entrepot',
            array('action'=>'edit', 'id' => $entrepot->id));?>">Modifier</a>
        <a href="<?php echo $this->url('entrepot',
            array('action'=>'delete', 'id' => $entrepot->id));?>">Supprimer</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php else : ?>

<p> Aucun produit au stock </p>

<?php endif; ?>