<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Supprimer un produit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes-vous sûr de vouloir supprimer le produit
    '<?php echo $this->escapeHtml($produit->nom); ?>' ?
</p>
<?php
$url = $this->url('produit', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $produit->id; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>