<?php
// module/Album/view/produit/produit/index.phtml:

$title = 'Mes Produits';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('produit', array('action'=>'add'));?>">Nouveau produit</a>
</p>

<table class="table">
<tr>
    <th>Nom</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($produits as $produit) : ?>
<tr>
    <td><?php echo $this->escapeHtml($produit->libelle);?></td>
    <td>
        <a class="btn" href="<?php echo $this->url('produit',
            array('action'=>'edit', 'id' => $produit->id));?>">Modifier</a>
        <a class="btn" href="<?php echo $this->url('produit',
            array('action'=>'delete', 'id' => $produit->id));?>">Supprimer</a>
    </td>
</tr>
<?php endforeach; ?>
</table>